name=pypilot-event-loop
version=0.1.0
author=bareboat-necessities
maintainer=bareboat-necessities
sentence=Portable scheduler for pypilot-cpp.
category=Other
url=https://github.com/bareboat-necessities/pypilot-event-loop
architectures=*
includes=pypilot_event_loop.hpp
